"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from requests.auth import AuthBase

def Client(url: str, headers: Dict[str, Any] = ..., auth: Optional[AuthBase] = ...): # -> Type[client_instance_base]:
    class client_instance_base(type):
        ...
