"""
This type stub file was generated by pyright.
"""

from abc import ABC
from typing import Any, Callable, Dict, Optional

def default_error_func(status_code: int, content: Dict[str, Any]) -> bool:
    ...

class Error(ABC):
    SLUG = ...
    def __init__(self, code: int, message: str, error_func: Optional[Callable[[int, Dict[str, Any]], bool]] = ...) -> None:
        ...

    def __set_name__(self, owner: Any, name: str): # -> None:
        ...

    def __get__(self, obj: Any, objtype: Any = ...): # -> Any:
        ...

    def __set__(self, obj: Any, value: Any): # -> None:
        ...

    def set_api_name(self, name: str): # -> None:
        ...

    def is_error(self, status_code: int, content: Dict[str, Any]) -> Optional[bool]:
        ...

    @property
    def code(self) -> int:
        ...

    @property
    def message(self) -> str:
        ...
