"""
This type stub file was generated by pyright.
"""

import datetime

class RateLimit:
    def __init__(self, max_requests: int, time_frame: datetime.timedelta) -> None:
        ...

    def can_make_request(self) -> bool:
        """
        Returns true if the rate limit will not be exceeded
        by making another request
        """
        ...

    def make_request(self) -> None:
        """
        increments the can make request counter
        """
        ...

    def request_wait_time(self) -> int:
        """
        Returns the time in microseconds to wait before the next request
        """
        ...
