"""
This type stub file was generated by pyright.
"""

from sd_utils.api.rate_limit import RateLimit
from sd_utils.api.error import Error
from typing import Any, Dict, List, Optional, Set, Union
from requests.auth import AuthBase

logger = ...
class Request:
    def __init__(self, method: str, endpoint: str, body: Dict[str, Any] = ..., auth: Union[AuthBase, None] = ..., documentation: str = ..., rate_limits: List[RateLimit] = ...) -> None:
        ...

    @property
    def documentation(self) -> str:
        ...

    def __call__(self, query: str = ..., body: Dict[str, Any] = ...) -> Any:
        ...

    def configure(self, base_url: str, headers: Dict[str, Any], auth: Optional[AuthBase], errors: Set[Error]): # -> None:
        ...
