"""
This type stub file was generated by pyright.
"""

import logging
from collections import namedtuple
from .client import Client
from .appinfo import AppInfo
from .user import ClientUser, Profile, User
from .emoji import Emoji
from .partial_emoji import PartialEmoji
from .activity import *
from .channel import *
from .guild import Guild
from .flags import *
from .relationship import Relationship
from .member import Member, VoiceState
from .message import *
from .asset import Asset
from .errors import *
from .calls import CallMessage, GroupCall
from .permissions import PermissionOverwrite, Permissions
from .role import Role, RoleTags
from .file import File
from .colour import Color, Colour
from .integrations import Integration, IntegrationAccount
from .invite import Invite, PartialInviteChannel, PartialInviteGuild
from .template import Template
from .widget import Widget, WidgetChannel, WidgetMember
from .object import Object
from .reaction import Reaction
from . import abc, opus, utils
from .enums import *
from .embeds import Embed
from .mentions import AllowedMentions
from .shard import AutoShardedClient, ShardInfo
from .player import *
from .webhook import *
from .voice_client import VoiceClient, VoiceProtocol
from .audit_logs import AuditLogChanges, AuditLogDiff, AuditLogEntry
from .raw_models import *
from .team import *
from .sticker import Sticker

"""
Discord API Wrapper
~~~~~~~~~~~~~~~~~~~

A basic wrapper for the Discord API.

:copyright: (c) 2015-2020 Rapptz
:license: MIT, see LICENSE for more details.

"""
__title__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
__version__ = ...
__path__ = ...
VersionInfo = ...
version_info = ...
