"""
This type stub file was generated by pyright.
"""

from .flags import BaseFlags, alias_flag_value, fill_with_flags, flag_value

"""
The MIT License (MIT)

Copyright (c) 2015-2020 Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
class permission_alias(alias_flag_value):
    ...


def make_permission_alias(alias): # -> (func: Unknown) -> permission_alias:
    ...

@fill_with_flags()
class Permissions(BaseFlags):
    """Wraps up the Discord permission value.

    The properties provided are two way. You can set and retrieve individual
    bits using the properties as if they were regular bools. This allows
    you to edit permissions.

    .. versionchanged:: 1.3
        You can now use keyword arguments to initialize :class:`Permissions`
        similar to :meth:`update`.

    .. container:: operations

        .. describe:: x == y

            Checks if two permissions are equal.
        .. describe:: x != y

            Checks if two permissions are not equal.
        .. describe:: x <= y

            Checks if a permission is a subset of another permission.
        .. describe:: x >= y

            Checks if a permission is a superset of another permission.
        .. describe:: x < y

             Checks if a permission is a strict subset of another permission.
        .. describe:: x > y

             Checks if a permission is a strict superset of another permission.
        .. describe:: hash(x)

               Return the permission's hash.
        .. describe:: iter(x)

               Returns an iterator of ``(perm, value)`` pairs. This allows it
               to be, for example, constructed as a dict or a list of pairs.
               Note that aliases are not shown.

    Attributes
    -----------
    value: :class:`int`
        The raw value. This value is a bit array field of a 53-bit integer
        representing the currently available permissions. You should query
        permissions via the properties rather than using this raw value.
    """
    __slots__ = ...
    def __init__(self, permissions=..., **kwargs) -> None:
        ...

    def is_subset(self, other): # -> bool:
        """Returns ``True`` if self has the same or fewer permissions as other."""
        ...

    def is_superset(self, other): # -> bool:
        """Returns ``True`` if self has the same or more permissions as other."""
        ...

    def is_strict_subset(self, other): # -> Literal[False]:
        """Returns ``True`` if the permissions on other are a strict subset of those on self."""
        ...

    def is_strict_superset(self, other): # -> Literal[False]:
        """Returns ``True`` if the permissions on other are a strict superset of those on self."""
        ...

    __le__ = ...
    __ge__ = ...
    __lt__ = ...
    __gt__ = ...
    @classmethod
    def none(cls): # -> Permissions:
        """A factory method that creates a :class:`Permissions` with all
        permissions set to ``False``."""
        ...

    @classmethod
    def all(cls): # -> Permissions:
        """A factory method that creates a :class:`Permissions` with all
        permissions set to ``True``."""
        ...

    @classmethod
    def all_channel(cls): # -> Permissions:
        """A :class:`Permissions` with all channel-specific permissions set to
        ``True`` and the guild-specific ones set to ``False``. The guild-specific
        permissions are currently:

        - manage_guild
        - kick_members
        - ban_members
        - administrator
        - change_nickname
        - manage_nicknames
        """
        ...

    @classmethod
    def general(cls): # -> Permissions:
        """A factory method that creates a :class:`Permissions` with all
        "General" permissions from the official Discord UI set to ``True``."""
        ...

    @classmethod
    def text(cls): # -> Permissions:
        """A factory method that creates a :class:`Permissions` with all
        "Text" permissions from the official Discord UI set to ``True``."""
        ...

    @classmethod
    def voice(cls): # -> Permissions:
        """A factory method that creates a :class:`Permissions` with all
        "Voice" permissions from the official Discord UI set to ``True``."""
        ...

    def update(self, **kwargs): # -> None:
        r"""Bulk updates this permission object.

        Allows you to set multiple attributes by using keyword
        arguments. The names must be equivalent to the properties
        listed. Extraneous key/value pairs will be silently ignored.

        Parameters
        ------------
        \*\*kwargs
            A list of key/value pairs to bulk update permissions with.
        """
        ...

    def handle_overwrite(self, allow, deny): # -> None:
        ...

    @flag_value
    def create_instant_invite(self): # -> int:
        """:class:`bool`: Returns ``True`` if the user can create instant invites."""
        ...

    @flag_value
    def kick_members(self): # -> int:
        """:class:`bool`: Returns ``True`` if the user can kick users from the guild."""
        ...

    @flag_value
    def ban_members(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can ban users from the guild."""
        ...

    @flag_value
    def administrator(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user is an administrator. This role overrides all other permissions.

        This also bypasses all channel-specific overrides.
        """
        ...

    @flag_value
    def manage_channels(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can edit, delete, or create channels in the guild.

        This also corresponds to the "Manage Channel" channel-specific override."""
        ...

    @flag_value
    def manage_guild(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can edit guild properties."""
        ...

    @flag_value
    def add_reactions(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can add reactions to messages."""
        ...

    @flag_value
    def view_audit_log(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can view the guild's audit log."""
        ...

    @flag_value
    def priority_speaker(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can be more easily heard while talking."""
        ...

    @flag_value
    def stream(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can stream in a voice channel."""
        ...

    @flag_value
    def read_messages(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can read messages from all or specific text channels."""
        ...

    @make_permission_alias('read_messages')
    def view_channel(self): # -> int:
        """:class:`bool`: An alias for :attr:`read_messages`.

        .. versionadded:: 1.3
        """
        ...

    @flag_value
    def send_messages(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can send messages from all or specific text channels."""
        ...

    @flag_value
    def send_tts_messages(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can send TTS messages from all or specific text channels."""
        ...

    @flag_value
    def manage_messages(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can delete or pin messages in a text channel.

        .. note::

            Note that there are currently no ways to edit other people's messages.
        """
        ...

    @flag_value
    def embed_links(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user's messages will automatically be embedded by Discord."""
        ...

    @flag_value
    def attach_files(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can send files in their messages."""
        ...

    @flag_value
    def read_message_history(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can read a text channel's previous messages."""
        ...

    @flag_value
    def mention_everyone(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user's @everyone or @here will mention everyone in the text channel."""
        ...

    @flag_value
    def external_emojis(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can use emojis from other guilds."""
        ...

    @make_permission_alias('external_emojis')
    def use_external_emojis(self): # -> int:
        """:class:`bool`: An alias for :attr:`external_emojis`.

        .. versionadded:: 1.3
        """
        ...

    @flag_value
    def view_guild_insights(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can view the guild's insights.

        .. versionadded:: 1.3
        """
        ...

    @flag_value
    def connect(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can connect to a voice channel."""
        ...

    @flag_value
    def speak(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can speak in a voice channel."""
        ...

    @flag_value
    def mute_members(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can mute other users."""
        ...

    @flag_value
    def deafen_members(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can deafen other users."""
        ...

    @flag_value
    def move_members(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can move users between other voice channels."""
        ...

    @flag_value
    def use_voice_activation(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can use voice activation in voice channels."""
        ...

    @flag_value
    def change_nickname(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can change their nickname in the guild."""
        ...

    @flag_value
    def manage_nicknames(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can change other user's nickname in the guild."""
        ...

    @flag_value
    def manage_roles(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can create or edit roles less than their role's position.

        This also corresponds to the "Manage Permissions" channel-specific override.
        """
        ...

    @make_permission_alias('manage_roles')
    def manage_permissions(self): # -> int:
        """:class:`bool`: An alias for :attr:`manage_roles`.

        .. versionadded:: 1.3
        """
        ...

    @flag_value
    def manage_webhooks(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can create, edit, or delete webhooks."""
        ...

    @flag_value
    def manage_emojis(self): # -> int:
        """:class:`bool`: Returns ``True`` if a user can create, edit, or delete emojis."""
        ...



def augment_from_permissions(cls):
    ...

@augment_from_permissions
class PermissionOverwrite:
    r"""A type that is used to represent a channel specific permission.

    Unlike a regular :class:`Permissions`\, the default value of a
    permission is equivalent to ``None`` and not ``False``. Setting
    a value to ``False`` is **explicitly** denying that permission,
    while setting a value to ``True`` is **explicitly** allowing
    that permission.

    The values supported by this are the same as :class:`Permissions`
    with the added possibility of it being set to ``None``.

    .. container:: operations

        .. describe:: x == y

            Checks if two overwrites are equal.
        .. describe:: x != y

            Checks if two overwrites are not equal.
        .. describe:: iter(x)

           Returns an iterator of ``(perm, value)`` pairs. This allows it
           to be, for example, constructed as a dict or a list of pairs.
           Note that aliases are not shown.

    Parameters
    -----------
    \*\*kwargs
        Set the value of permissions by their name.
    """
    __slots__ = ...
    def __init__(self, **kwargs) -> None:
        ...

    def __eq__(self, other) -> bool:
        ...

    def pair(self): # -> tuple[Permissions, Permissions]:
        """Tuple[:class:`Permissions`, :class:`Permissions`]: Returns the (allow, deny) pair from this overwrite."""
        ...

    @classmethod
    def from_pair(cls, allow, deny): # -> PermissionOverwrite:
        """Creates an overwrite from an allow/deny pair of :class:`Permissions`."""
        ...

    def is_empty(self): # -> bool:
        """Checks if the permission overwrite is currently empty.

        An empty permission overwrite is one that has no overwrites set
        to ``True`` or ``False``.

        Returns
        -------
        :class:`bool`
            Indicates if the overwrite is empty.
        """
        ...

    def update(self, **kwargs): # -> None:
        r"""Bulk updates this permission overwrite object.

        Allows you to set multiple attributes by using keyword
        arguments. The names must be equivalent to the properties
        listed. Extraneous key/value pairs will be silently ignored.

        Parameters
        ------------
        \*\*kwargs
            A list of key/value pairs to bulk update with.
        """
        ...

    def __iter__(self): # -> Generator[tuple[Unknown, Unknown | None], None, None]:
        ...
